# Generated by Django 3.1.7 on 2021-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_about_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
        migrations.AddField(
            model_name='about',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
