# Generated by Django 3.1.7 on 2021-06-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210616_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
