# Generated by Django 3.1.7 on 2021-06-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_about_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='freelance',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
