# Generated by Django 3.1.7 on 2021-06-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_skill_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='job',
        ),
    ]
