# Generated by Django 3.1.7 on 2021-07-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210701_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img/'),
        ),
    ]
