# Generated by Django 3.1.7 on 2021-07-29 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210729_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='whatsapp_link',
            new_name='whatsapp',
        ),
    ]
